apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: channel-carrier
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: channel-carrier
  chart:
    git: ssh://git@github.com/vangarasandeep/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://aedb1188bc7b711eab6f5060b7f7fdf6-993300541.ap-southeast-1.elb.amazonaws.com:9000
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.org1ambassador.blockchaincloudpoc.com:8443
    channeltx: |-
      CrQDChgKFggCGgYI2f3h+AUiCmFsbGNoYW5uZWwSlwMKlAMKCmFsbGNoYW5uZWwSZhJUCgtBcHBs
      aWNhdGlvbhJFEhAKDHdhcmVob3VzZU1TUBIAEhMKD21hbnVmYWN0dXJlck1TUBIAEg4KCmNhcnJp
      ZXJNU1ASABIMCghzdG9yZU1TUBIAGg4KCkNvbnNvcnRpdW0SABqdAhLxAQoLQXBwbGljYXRpb24S
      4QEIARIMCghzdG9yZU1TUBIAEhAKDHdhcmVob3VzZU1TUBIAEhMKD21hbnVmYWN0dXJlck1TUBIA
      Eg4KCmNhcnJpZXJNU1ASABokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYxXzESABoGQWRtaW5zIiIK
      BkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVh
      ZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMa
      JwoKQ29uc29ydGl1bRIZEhcKFVN1cHBseUNoYWluQ29uc29ydGl1bQ==